name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  push:
    runs-on: ubuntu-20.04
    environment: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: kartoza/docker-geoserver
          ref: v2.21.1
          path: docker-geoserver
      - name: Load ENV file
        run: grep -v '^#'  $GITHUB_WORKSPACE/docker-geoserver/.env >> $GITHUB_ENV
      - name: output-tag
        run: |
          echo "IMAGE_TAG=${{ env.GS_VERSION }}-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=${{ env.GS_VERSION }}-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Build Docker Image
        run: |
          cd $GITHUB_WORKSPACE/docker-geoserver
          sudo docker build -t umeraltaf/geoserver:${{ env.IMAGE_TAG }} .
      - name: Push to Repo
        run: docker image push umeraltaf/geoserver:"${{ env.IMAGE_TAG }}"